In [1]:
import torch
from torch import nn
import torch.nn.functional as F


In [11]:
x = torch.randn(2, 3)
y = torch.randn(2, 3)
print(x)
print(y)

list1 = []
list1.append(x)
list1.append(y)

torch.stack(list1, 1)

tensor([[ 1.1893, -0.6466,  0.5855],
        [ 0.8463, -0.8287, -1.5870]])
tensor([[-1.4208,  0.3020,  0.5809],
        [-0.1431, -1.0845,  0.5382]])


tensor([[[ 1.1893, -0.6466,  0.5855],
         [-1.4208,  0.3020,  0.5809]],

        [[ 0.8463, -0.8287, -1.5870],
         [-0.1431, -1.0845,  0.5382]]])

In [14]:
torch.stack(list1, 0)

tensor([[[ 1.1893, -0.6466,  0.5855],
         [ 0.8463, -0.8287, -1.5870]],

        [[-1.4208,  0.3020,  0.5809],
         [-0.1431, -1.0845,  0.5382]]])